load creol-interpreter .
mod PROGRAM is
protecting CREOL-SIMULATOR .
op classes : -> Configuration [ctor] .
eq classes =
< "MutRec" : Class | Inh: (noInh),
  Param: (noVid),
  Att: (noSubst),
  Mtds: (< "init" : Method | Param: noVid, Att: "_" |-> null, Code: skip ; return ( emp ) > ,
    < "run" : Method | Param: noVid, Att: "_" |-> null, Code: skip ; return ( emp ) > ,
    < "doit" : Method | Param: "other", Att: "other" |-> null , "label:0" |-> null , "_" |-> null, Code: call( "label:0" ; "other" ; "doit" ; "this" ) ; get( "label:0" ; noVid ) ; return ( emp ) >),
  Ocnt: 0 >

< "Test" : Class | Inh: (noInh),
  Param: (noVid),
  Att: ("m1" |-> null , "m2" |-> null),
  Mtds: (< "init" : Method | Param: noVid, Att: "_" |-> null, Code: new( "m1" ; "MutRec" ; emp ) ; new( "m2" ; "MutRec" ; emp ) ; return ( emp ) > ,
    < "run" : Method | Param: noVid, Att: "label:0" |-> null , "_" |-> null, Code: call( "label:0" ; "m1" ; "doit" ; "m2" ) ; free( "label:0" ) ; return ( emp ) > ,
    < "doit" : Method | Param: "other", Att: "other" |-> null , "_" |-> null, Code: skip ; return ( emp ) >),
  Ocnt: 0 >

.
endm
