load creol-interpreter
mod PROGRAM is
protecting CREOL-SIMULATOR .
op init : -> Configuration [ctor] .
eq init =
< "Test" : Cl | Inh: noInh, Par: noVid, Att: noSubst, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: "label:0" |-> null , "a" |-> null, Code: "a" ::= new "Test" ( emp ) ; "label:0" ! "a" . "m" ( emp ) ; ( "label:0" ? ( noVid ) )  ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "m" : Mtdname | Param: noVid, Latt: "label:0" |-> null, Code: "label:0" ! "caller" . "m" ( emp ) ; ( "label:0" ? ( noVid ) )  ; return ( emp ) >, Ocnt: 0 >

.
endm
