load creol-interpreter .
mod PROGRAM is
  protecting CREOL-SIMULATOR .
  op classes : -> Configuration [ctor] .
  eq classes =
    < "Weirdness" : Class | Inh: noInh, Param: noVid, Att: "c" |-> null,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null,
              Code: assign( ( "c" @ "Weirdness" ) ; bool(false) ) ;
              return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "_" |-> null, Code: skip ;
              return ( emp ) >,
            < "m" : Method | Param: noVid, Att: "_" |-> null, Code: release ;
              await "c" ; return ( emp ) >,
            < "n" : Method | Param: noVid, Att: "_" |-> null,
              Code: assign( "c" ; bool(true) ) ; return ( emp ) >,
      Ocnt: 0 >
    
    < "Test" : Class | Inh: noInh, Param: noVid, Att: noSubst,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null, Code: skip ;
              return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "label:1" |-> null,
              "label:0" |-> null, "w" |-> null, "_" |-> null,
              Code: new( "w" ; "Weirdness" ; emp ) ; call( "label:0" ; "w" ;
              "m" ; emp ) ; free( "label:0" ) ; call( "label:1" ; "w" ; "n" ;
              emp ) ; free( "label:1" ) ; return ( emp ) >,
      Ocnt: 0 > .
endm

