load creol-interpreter .
mod PROGRAM is
  protecting CREOL-SIMULATOR .
  op classes : -> Configuration [ctor] .
  eq classes =
    < "Test" : Class | Inh: noInh, Param: noVid, Att: noSubst,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null, Code: skip ;
              return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "ccglab0" |-> null, "r" |->
              null, "_" |-> null,
              Code: call( "ccglab0" ; "this" ; "m" ; emp ) ;
              get( "ccglab0" ; "r" ) ; free( "ccglab0" ) ; return ( emp ) >,
            < "m" : Method | Param: noVid, Att: "r" |-> null, "ccglab0" |->
              null, "_" |-> null,
              Code: (call( "ccglab0" ; "this" ; "m" ; emp ) ;
                      get( "ccglab0" ; "r" ) ; free( "ccglab0" ) ;
                      assign( "r" ; "+" ( "r" :: int(1) ) ) []
                      assign( "r" ; int(1) ))
              ; return ( "r" ) >,
      Ocnt: 0 > .
endm

