load creol-interpreter .
mod PROGRAM is
  protecting CREOL-SIMULATOR .
  op classes : -> Configuration [ctor] .
  eq classes =
    < "Test" : Class | Inh: noInh, Param: noVid, Att: "depth" |-> null, "max"
      |-> null,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null,
              Code: assign( ( "depth" @ "Test" ), ( "max" @ "Test" ) ; int(0)
              :: int(3) ) ; return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "label:0" |-> null, "_" |->
              null, Code: call( "label:0" ; "this" ; "test" ; emp ) ;
              get( "label:0" ; noVid ) ; free( "label:0" ) ; return ( emp ) >,
            < "test" : Method | Param: noVid, Att: "label:0" |-> null, "temp"
              |-> null, "_" |-> null, Code: assign( "depth" ; "+" ( "depth"
              :: int(1) ) ) ; assign( "temp" ; "depth" ) ; if "<=" ( "depth"
              :: "max" ) th call( "label:0" ; "this" ; "test" ; emp ) ;
              get( "label:0" ; noVid ) ; free( "label:0" ) el skip fi ; await
              "=" ( "depth" :: "temp" ) ; assign( "depth" ; "-" ( "depth" ::
              int(1) ) ) ; return ( emp ) >,
      Ocnt: 0 > .
endm

