#! /bin/sh
#
# menhir-sh -- Replacement for a missing menhir binary.
#
# This file is part of creoltools
#
# Written and Copyright (c) 2007 by Marcel Kyas
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#
cat 1>&2 <<EOF
ERROR: menhir is needed, but is not installed.

You should only need it if you modified a \`.mly' file.
You can get \`menhir' from <http://cristal.inria.fr/~fpottier/menhir/>
or from <http://godi.ocaml-programming.de/> to compile the creoltools.  If
you use godi, the godi_console can help you in installing menhir.
EOF
exit 2
