load interpreter
mod PROGRAM is
pr INTERPRETER .
op init : -> Configuration [ctor] .
eq init =
< "Alarmclock" : Cl | Inh: noInh, Par: noAid, Att: "now" |-> null, Mtds: 
  < "run" : Mtdname | Param: noAid, Latt: noSubst, Code: "now" ::= int(0) ; return ( emp ) > *
  < "wakeme" : Mtdname | Param: "n", Latt: "n" |-> null , "alarmsetting" |-> null, Code: "alarmsetting" ::= "+" ( "now" # "n" ) ; ( await ">=" ( "now" # "alarmsetting" ) ) ; return ( emp ) > *
  < "tick" : Mtdname | Param: noAid, Latt: noSubst, Code: "now" ::= "+" ( "now" # int(1) ) ; return ( emp ) >, Ocnt: 0 >

.
endm
