*** Shows the bug.
***
*** This test needs about
***  60 sec, 410 MiB memory on my home
*** 135 sec, 220 MiB memory on my laptop.
*** Therefore, it is disabled at the user installation.
***
in AsyncSieveBuggy .

search [1] in PROGRAM : init main("Generator", emp) =>+
  < O:Oid : "Sieve" | Att: A:Subst, "p" |-> int(9), Pr:
                      L:Subst, SL:StmList, PrQ: W:MProc, Lcnt: N:Nat >
  conf:Configuration .
