***
*** Datatypes.maude -- Test suite for the data types module.
***
*** Copyright (c) 2007
***
*** The purpose of this file is to create the files `prelude.creol'
*** and `modelcheck.creol'.  These files have to be processed with
*** m4, with either one of `CREOL' or `MODELCHECK' defined.
***
*** This program is free software; you can redistribute it and/or
*** modify it under the terms of the GNU General Public License as
*** published by the Free Software Foundation; either version 2 of the
*** License, or (at your option) any later version.
***
*** This program is distributed in the hope that it will be useful, but
*** WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*** General Public License for more details.
***
*** You should have received a copy of the GNU General Public License
*** along with this program; if not, write to the Free Software
*** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
*** 02111-1307, USA.
***

set show timing off .
set show advise off .
load creol-datatypes

red in CREOL-DATA-SIG : emp .
red in CREOL-DATA-SIG : emp :: emp .
red in CREOL-DATA-VIDLIST : noVid .
red in CREOL-DATA-VIDLIST : noVid , noVid .
red in CREOL-DATA-SIG : "a" .
red in CREOL-DATA-SIG : "a" :: "a" .
red in CREOL-DATA-VIDLIST : "a" , "a" .
red in CREOL-EXPRESSION : "a" ( "a" ) .
red in CREOL-DATA-SIG : null .
red in CREOL-DATA-SIG : null :: null .
red in CREOL-DATA-SIG : null :: "a" .
red in CREOL-EXPRESSION : null :: ("a" ( "a" )) :: null .
red in CREOL-EXPRESSION : ("a" ( "a" )) :: null .
red in CREOL-DATA-VIDLIST : null , "a" .
red in CREOL-DATA-BOOL : bool(true) .
red in CREOL-DATA-BOOL : "=" ( null :: null ) .
red in CREOL-DATA-BOOL : "/=" ( null :: null ) .
red in CREOL-DATA-BOOL : "~" ( "=" ( null :: null ) ) .
red in CREOL-DATA-BOOL : "||" ( ("=" ( null :: null )) :: ("=" ( null :: null )) ) .
red in CREOL-DATA-LIST : "|-" (list(int(1) :: int(2)) :: "head" (list(int(1) :: int(2))) ) .
red in CREOL-DATA-LIST : "#" (list(emp)) .
red in CREOL-DATA-LIST : "#" (list(int(1) :: int(2))) .

quit
