load interpreter
mod PROGRAM is
pr CREOL-INTERPRETER .
op init : -> Configuration [ctor] .
eq init =
< "Test" : Cl | Inh: noInh, Par: noAid, Att: "x" |-> null , "y" |-> null, Mtds: 
  < "init" : Mtdname | Param: noAid, Latt: noSubst, Code: "x" ::= int(0) ; "y" ::= int(0) ; return ( emp ) > *
  < "run" : Mtdname | Param: noAid, Latt: noSubst, Code: ( "x" ::= int(1) ; "y" ::= int(2) ||| "y" ::= int(1) ; "x" ::= int(2) ) ; return ( emp ) >, Ocnt: 0 >

.
endm
