***
*** Interpreter.maude -- Test cases for the interpreter.
***
*** Copyright (c) 2007
***
*** This program is free software; you can redistribute it and/or
*** modify it under the terms of the GNU General Public License as
*** published by the Free Software Foundation; either version 2 of the
*** License, or (at your option) any later version.
***
*** This program is distributed in the hope that it will be useful, but
*** WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*** General Public License for more details.
***
*** You should have received a copy of the GNU General Public License
*** along with this program; if not, write to the Free Software
*** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
*** 02111-1307, USA.
***

set show timing off .
set show advise off .
load creol-modelchecker .

mod TEST-TAILCALL is
  protecting CREOL-SIMULATOR .
  op classes : -> Configuration .
  eq classes =
    < "Tailcall" : Class | Inh: noInh, Param: "x", Att: "x" |-> null, Mtds:
	< "init" : Method | Param: noVid, Att: noSubst, Code: return(emp) > ,
	< "run" : Method | Param: noVid, Att: noSubst, Code:
          if "<" ( int(0) :: "x" ) th assign ( "x" ; "-" ( "x" :: int(1) ) ) ;
	    statictail("run" ; None ; None ; emp) el return(emp) fi >,
      Ocnt: 0 > .

endm

red in TEST-TAILCALL : main(classes, "Tailcall", int(5)) .

rew[1] in TEST-TAILCALL : main(classes, "Tailcall", int(5)) .

rew in TEST-TAILCALL : main(classes, "Tailcall", int(5)) .

quit
