load creol-interpreter
mod PROGRAM is
pr CREOL-INTERPRETER .
op init : -> Configuration [ctor] .
eq init =
< "Test" : Cl | Inh: noInh, Par: noVid, Att: noSubst, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: "a" |-> null, Code: "a" ::= new "A" ( emp ) ; "sync.0" ! "a" . "m" ( emp ) ; ( "sync.0" ? ( noVid ) )  ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "m" : Mtdname | Param: noVid, Latt: noSubst, Code: "sync.0" ! "caller" . "m" ( emp ) ; ( "sync.0" ? ( noVid ) )  ; return ( emp ) >, Ocnt: 0 >

.
endm
