load interpreter
mod PROGRAM is
pr CREOL-INTERPRETER .
op init : -> Configuration [ctor] .
eq init =
< "Buffer" : Cl | Inh: noInh, Par: noAid, Att: "cell" |-> null , "ctr" |-> null , "next" |-> null, Mtds: 
  < "init" : Mtdname | Param: noAid, Latt: noSubst, Code: "ctr" ::= int(0) ; return ( emp ) > *
  < "run" : Mtdname | Param: noAid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "put" : Mtdname | Param: "x", Latt: "x" |-> null, Code: if "=" ( "ctr" # int(0) ) th "cell" ::= "x" el if "=" ( "next" # null ) th "next" ::= new "Buffer" ( emp ) el skip fi ; "sync.0" ! "next" . "put" ( "x" ) ; ( "sync.0" ? ( noAid ) )  fi ; "ctr" ::= "+" ( "ctr" # int(1) ) ; return ( emp ) > *
  < "get" : Mtdname | Param: noAid, Latt: "x" |-> null, Code: ( await ">" ( "ctr" # int(0) ) ) ; if "/=" ( "cell" # null ) th "x" ::= "cell" el "sync.0" ! "next" . "get" ( emp ) ; ( "sync.0" ? ( "x" ) )  fi ; "ctr" ::= "-" ( "ctr" # int(1) ) ; "cell" ::= null ; return ( "x" ) >, Ocnt: 0 >

.
endm
