load creol-interpreter
mod PROGRAM is
pr CREOL-INTERPRETER .
op init : -> Configuration [ctor] .
eq init =
< "Alarmclock" : Cl | Inh: noInh, Par: noVid, Att: "clock" |-> null, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: noSubst, Code: "clock" ::= int(0) ; return ( emp ) > *
  < "wakeme" : Mtdname | Param: "n", Latt: "n" |-> null , "alarmsetting" |-> null, Code: "alarmsetting" ::= "+" ( "clock" # "n" ) ; ( await ">=" ( "clock" # "alarmsetting" ) ) ; return ( emp ) > *
  < "tick" : Mtdname | Param: noVid, Latt: noSubst, Code: "clock" ::= "+" ( "clock" # int(1) ) ; return ( emp ) >, Ocnt: 0 >

.
endm
