load creol-interpreter .
mod PROGRAM is
protecting CREOL-SIMULATOR .
op classes : -> Configuration [ctor] .
eq classes =
< "Alarmclock" : Cl | Inh: (noInh),
  Par: (noVid),
  Att: ("clock" |-> null),
  Mtds: (< "init" : Mtdname | Param: noVid, Latt: "_" |-> null, Code: "clock" ::= int(0) ; return ( emp ) > *
    < "run" : Mtdname | Param: noVid, Latt: "label:0" |-> null , "_" |-> null, Code: "clock" ::= "+" ( "clock" :: int(1) ) ; ( "label:0" ! "this" . "run" (emp ) )  ; free( "label:0" ) ; return ( emp ) > *
    < "wakeme" : Mtdname | Param: "n", Latt: "n" |-> null , "alarmsetting" |-> null , "_" |-> null, Code: "alarmsetting" ::= "+" ( "clock" :: "n" ) ; ( await ">=" ( "clock" :: "alarmsetting" ) ) ; return ( emp ) >),
  Ocnt: 0 >

.
endm
