load creol-interpreter
mod PROGRAM is
pr CREOL-INTERPRETER .
op init : -> Configuration [ctor] .
eq init =
< "BoundedBuffer" : Cl | Inh: noInh, Par: noVid, Att: "buffer" |-> null , "max" |-> null , "n" |-> null, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "append" : Mtdname | Param: "d", Latt: "d" |-> null, Code: ( await "<" ( "n" # "max" ) ) ; "buffer" ::= "|-" ( "buffer" # "d" ) ; return ( emp ) > *
  < "remove" : Mtdname | Param: noVid, Latt: "d" |-> null, Code: ( await ">" ( "n" # int(0) ) ) ; "d" ::= "head" ( "buffer" ) ; "buffer" ::= "tail" ( "buffer" ) ; return ( "d" ) >, Ocnt: 0 >

< "Producer" : Cl | Inh: noInh, Par: "b", Att: "b" |-> null, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: noSubst, Code: ( ".anon" ! "this" . "loop" (int(0) ) )  ; free( ".anon" ) ; return ( emp ) > *
  < "loop" : Mtdname | Param: "i", Latt: "i" |-> null, Code: "sync.0" ! "b" . "append" ( "i" ) ; ( "sync.0" ? ( noVid ) )  ; ( ".anon" ! "this" . "loop" ("+" ( "i" # int(1) ) ) )  ; free( ".anon" ) ; return ( emp ) >, Ocnt: 0 >

< "Consumer" : Cl | Inh: noInh, Par: "b", Att: "b" |-> null, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: "y" |-> null, Code: "sync.0" ! "b" . "remove" ( emp ) ; ( "sync.0" ? ( "y" ) )  ; ( ".anon" ! "this" . "run" (emp ) )  ; free( ".anon" ) ; return ( emp ) >, Ocnt: 0 >

< "Starter" : Cl | Inh: noInh, Par: noVid, Att: noSubst, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: "b" |-> null , "p" |-> null , "c" |-> null, Code: "b" ::= new "BoundedBuffer" ( emp ) ; "p" ::= new "Producer" ( "b" ) ; "c" ::= new "Consumer" ( "b" ) ; return ( emp ) >, Ocnt: 0 >

.
endm
