load creol-interpreter .
mod PROGRAM is
  protecting CREOL-SIMULATOR .
  op state : -> State [ctor] .
  eq state = {
    < "CallAll" : Class | Inh: noInh, Param: noVid, Att: "outstanding" |->
      null, "list" |-> null, "results" |-> null,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null, Code: skip ;
              return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "_" |-> null, Code: skip ;
              return ( emp ) >,
            < "doit" : Method | Param: "l", Att: "l" |-> null, "ccglab0" |->
              null, "i" |-> null, "r" |-> null, "o" |-> null, "_" |-> null,
              Code: if "/=" ( "l" :: list(emp) ) th call( "r" ;
              "fst" ( "i" ) ; "m" ; "snd" ( "i" ) ) ;
              call( "ccglab0" ; "this" ; "doit" ; "tail" ( "l" ) ) ;
              get( "ccglab0" ; noVid ) ; free( "ccglab0" ) ; await ?("r") ;
              get( "r" ; "o" ) ; free( "r" ) ;
              assign( "results" ; "|-" ( "results" :: list("fst" ( "i" ) ::
              "o") ) ) el skip fi ; return ( emp ) >,
            < "call_all" : Method | Param: noVid, Att: "ccglab0" |-> null,
              "_" |-> null, Code: assign( "results" ; list(emp) ) ;
              call( "ccglab0" ; "this" ; "doit" ; "list" ) ;
              get( "ccglab0" ; noVid ) ; free( "ccglab0" ) ; await
              "=" ( "#" ( "results" ) :: "#" ( "list" ) ) ; return ( emp ) >,
      Ocnt: 0 > } .
endm

