load creol-interpreter .
mod PROGRAM is
protecting CREOL-SIMULATOR .
op classes : -> Configuration [ctor] .
eq classes =
< "DiscreteTimeout" : Class | Inh: (noInh),
  Param: ("other"),
  Att: ("other" |-> null , "clock" |-> null),
  Mtds: (< "init" : Method | Param: noVid, Att: "_" |-> null, Code: assign( ( "clock" @ "DiscreteTimeout" ) ; int(0) ) ; return ( emp ) > ,
    < "run" : Method | Param: noVid, Att: "label:0" |-> null , "_" |-> null, Code: assign( "clock" ; "+" ( "clock" :: int(1) ) ) ; call( "label:0" ; "this" ; "run" ; emp ) ; free( "label:0" ) ; return ( emp ) > ,
    < "timeout" : Method | Param: "n", Att: "n" |-> null , "result" |-> null , "timeout" |-> null , "l" |-> null , "_" |-> null, Code: assign( "timeout" ; "+" ( "clock" :: int(10) ) ) ; call( "l" ; "other" ; "m" ; emp ) ; ( ( await "&&" ( ?("l") :: "<=" ( "clock" :: "timeout" ) ) ) ; get( "l" ; noVid ) ; assign( "result" ; bool(true) ) [] ( await ">" ( "clock" :: "timeout" ) ) ; free( "l" ) ; assign( "result" ; bool(false) ) ) ; return ( "result" ) >),
  Ocnt: 0 >

.
endm
