load creol-interpreter
mod PROGRAM is
pr CREOL-INTERPRETER .
op init : -> Configuration [ctor] .
eq init =
< "Node" : Cl | Inh: noInh, Par: "db", Att: "db" |-> null, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "enquire" : Mtdname | Param: noVid, Latt: "files" |-> null , "label:0" |-> null, Code: "label:0" ! "db" . "listFiles" ( emp ) ; ( await ( "label:0" ?? ) ) ; ( "label:0" ? ( "files" ) )  ; return ( "files" ) > *
  < "getLength" : Mtdname | Param: "fId", Latt: "fId" |-> null , "lth" |-> null , "label:0" |-> null, Code: "label:0" ! "db" . "getLength" ( "fId" ) ; ( await ( "label:0" ?? ) ) ; ( "label:0" ? ( "lth" ) )  ; return ( "lth" ) > *
  < "getPack" : Mtdname | Param: "fId" , "pNbr", Latt: "fId" |-> null , "pNbr" |-> null , "pack" |-> null , "label:0" |-> null , "f" |-> null, Code: "label:0" ! "db" . "getFile" ( "fId" ) ; ( await ( "label:0" ?? ) ) ; ( "label:0" ? ( "f" ) )  ; "pack" ::= "at" ( "f" # "pNbr" ) ; return ( "pack" ) > *
  < "availFiles" : Mtdname | Param: "sList", Latt: "sList" |-> null , "files" |-> null , "l1" |-> null , "l2" |-> null, Code: if "=" ( "sList" # list(emp) ) th "files" ::= list(emp) el "l1" ! "head" ( "sList" ) . "enquire" ( emp ) ; "l2" ! "this" . "availFiles" ( "tail" ( "sList" ) ) ; ( await "&&" ( ( "l1" ?? ) # ( "l2" ?? ) ) ) ; ( "l1" ? ( noVid ) )  ; ( "l2" ? ( "files" ) )  fi ; return ( "files" ) > *
  < "reqFile" : Mtdname | Param: "sId" , "fId", Latt: "sId" |-> null , "fId" |-> null , "label:2" |-> null , "label:1" |-> null , "label:0" |-> null , "file" |-> null , "pack" |-> null , "lth" |-> null, Code: "label:0" ! "sId" . "getLength" ( "fId" ) ; ( await ( "label:0" ?? ) ) ; ( "label:0" ? ( "lth" ) )  ; while ">" ( "lth" # int(0) ) do "label:1" ! "sId" . "getPack" ( "fId" # "lth" ) ; ( await ( "label:1" ?? ) ) ; ( "label:1" ? ( "pack" ) )  ; "file" ::= "-|" ( "pack" # "file" ) ; "lth" ::= "-" ( "lth" # int(1) ) od  ; "label:2" ! "db" . "storeFile" ( "fId" # "file" ) ; free( "label:2" ) ; return ( emp ) >, Ocnt: 0 >

.
endm
