load creol-interpreter
mod PROGRAM is
protecting CREOL-SIMULATOR .
op init : -> Configuration [ctor] .
eq init =
< "Buffer" : Cl | Inh: noInh, Par: noVid, Att: "cell" |-> null , "ctr" |-> null , "next" |-> null, Mtds: 
  < "init" : Mtdname | Param: noVid, Latt: noSubst, Code: "ctr" ::= int(0) ; return ( emp ) > *
  < "run" : Mtdname | Param: noVid, Latt: noSubst, Code: skip ; return ( emp ) > *
  < "put" : Mtdname | Param: "x", Latt: "x" |-> null , "label:0" |-> null, Code: if "=" ( "ctr" :: int(0) ) th "cell" ::= "x" el if "=" ( "next" :: null ) th "next" ::= new "Buffer" ( emp ) el skip fi ; "label:0" ! "next" . "put" ( "x" ) ; ( "label:0" ? ( noVid ) )  fi ; "ctr" ::= "+" ( "ctr" :: int(1) ) ; return ( emp ) > *
  < "get" : Mtdname | Param: noVid, Latt: "x" |-> null , "label:0" |-> null, Code: ( await ">" ( "ctr" :: int(0) ) ) ; if "/=" ( "cell" :: null ) th "x" ::= "cell" el "label:0" ! "next" . "get" ( emp ) ; ( "label:0" ? ( "x" ) )  fi ; "ctr" ::= "-" ( "ctr" :: int(1) ) ; "cell" ::= null ; return ( "x" ) >, Ocnt: 0 >

.
endm
