\input texinfo	@c -*-texinfo-*-
@c %**start of header
@documentlanguage en
@setfilename creoltools.info
@settitle Creol Compiler
@c %**end of header
@afourpaper
@include version.texi

@copying
This manual is describing a Creol Compiler
(version @value{VERSION}, @value{UPDATED}).

Copyright @copyright{} 2007 Marcel Kyas.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end quotation
@end copying

@dircategory UML
@direntry
* creoltools:: A Creol Compiler.
@end direntry

@titlepage
@title Creol Compiler User Guide
@subtitle for version @value{VERSION}, @value{UPDATED}
@author Marcel Kyas
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top 

@insertcopying
@end ifnottex

@menu
* Introduction::        Introduction to Creol and its tools.
* Invocation::          How to invoke the compiler.
* Creol::               A description of the Creol language.
* CMC::                 Creol Machine Code.
* Licenses::            Your rights and freedoms.
* Index::               Index of concepts.
@end menu

@include introduction.texi
@include invocation.texi
@include creol.texi
@include cmc.texi

@node Licenses
@appendix Licenses

The software is licensed under the terms of the general public license,
the documentation is licensed under the terms of the free documentation
license.

@menu
* Copying::
* GNU Free Documentation License::
@end menu

@lowersections
@include gpl.texi
@raisesections
@include fdl.texi

@node Index
@unnumbered Index

@printindex cp

@bye
