\input texinfo	@c -*-texinfo-*-
@c %**start of header
@setfilename creoltools.info
@settitle @acronym{CREOL} Tools
@c %**end of header
@c @documentlanguage en
@documentencoding US-ASCII
@afourpaper
@include version.texi

@copying
This manual is describing Tools for @acronym{CREOL}
(version @value{VERSION}, @value{UPDATED}).

Copyright @copyright{} 2007, 2008 Marcel Kyas.

@quotation
This work has been financially supported by European Projects,
IST-33826 Credo and IST-2001-33522 Omega, the German Research Council,
and the Norwegian Research Council.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation.
@c ; with no Invariant Sections, with the Front-Cover texts being
@c ``A GNU Manual,'' and with the Back-Cover Texts as in (a) below.
A copy of the license is included in the section entitled ``GNU Free
Documentation License.''

@c (a) The FSF's Back-Cover Text is: ``You have freedom to copy and
@c modify this GNU Manual, like GNU software.  Copies published by the
@c Free Software Foundation raise funds for GNU development.''
@end quotation
@end copying

@dircategory @acronym{CREOL}
@direntry
* creoltools:: A @acronym{CREOL} Compiler.
@end direntry

@titlepage
@title @acronym{CREOL} Tools User Guide
@subtitle for version @value{VERSION}, @value{UPDATED}
@author Marcel Kyas
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top 

@insertcopying
@end ifnottex

@menu
* Introduction::          Introduction to @acronym{CREOL} and its tools.
* CREOL Tutorial::        An introduction to the @acronym{CREOL} language.
* CREOL Language::        A description of the @acronym{CREOL} language.
* CREOL Prelude::         The standard library for @acronym{CREOL}.
* Real-time CREOL::       Using @acronym{CREOL} for Timed Models.
* CREOL Machine Code::    @acronym{CREOL} Machine Code.
* Model-checking CREOL::  Using Maude to Model-Check @acronym{CREOL} programs.
* creolc::                How to use the @command{creolc} compiler.
* creolshell::            How to use the @command{creolshell}.
* Grammar::               The grammar definition of @acronym{CREOL}.
* FAQ::                   Frequently asked questions.
@c * Bibliography::          Further reading.
* Licenses::              Your rights and freedoms.
* Index::                 Index of concepts.
@end menu

@include introduction.texi
@include creoltut.texi
@include creol.texi
@include creollib.texi
@include creolrt.texi
@include cmc.texi
@include creolmc.texi
@include creolc.texi
@include creolshell.texi
@include grammar.texi
@include faq.texi

@c @include bibliography.texi
@c @include bugs.texi


@node Licenses
@appendix Licenses

The software is licensed under the terms of the GNU General Public
License.  The accompanying documentation is licensed under the terms of
the GNU Free Documentation License.

@menu
* Copying::
* GNU Free Documentation License::
@end menu

@lowersections
@include gpl.texi
@raisesections
@include fdl.texi

@node Index
@unnumbered Index

@printindex cp

@bye
@c The release history is maintained here to force an update of this file
@c with each release.  This will set version and date in @file{version.texi}
@c to its correct values.
@c
@c Version 0.0h (r1124) was released on January 11, 2008.
@c Version 0.0g (r901) was released on September 10, 2007.
@c Version 0.0f (r685) was released on Jul 10, 2007.
@c Version 0.0e (r595) was released on June 22, 2007.
@c Version 0.0d (r568) was released on June 17, 2007.
@c Version 0.0c (r494) was released on May 7, 2007.
@c Version 0.0b (r365) was released on March 16, 2007.
@c Version 0.0a (r275) was released on March 5, 2007.
