@node Introduction
@chapter Introduction

@acronym{CREOL}: An exciting mix of the best ingredients from many cultures!


@acronym{CREOL}: A formal framework for reflective component modelling

The goal of @acronym{CREOL} is to develop a formal framework and tool
for reasoning about dynamic and reflective modifications in
object-oriented open distributed systems, ensuring reliability and
correctness of the overall system.

@menu
* Overview::            What is @acronym{CREOL} about?
* Features of CREOL::   Features of @acronym{CREOL}.
@end menu


@node Overview
@section Overview

Open distributed systems consist of geographically spread system
components subject to run-time modifications. These systems are
becoming increasingly important in modern society, for instance for
safety-critical infrastructure. A major challenge for safety-critical
open distributed systems is to ensure the reliability and correctness
of the overall system when components are dynamically modified, so
that development, maintenance, and upgrade of system components happen
in a controlled manner.

The @acronym{CREOL} language contains programming constructs and
reasoning control in the context of open distributed systems, and in
particular the issue of maintenance control, taking an object-oriented
approach. The project focuses on support for component adaptability,
combined with a platform for executable specification and analysis of
system models. This allows an investigation at two levels: a
theoretical framework for reasoning about software and software
updates, and a tool for practical experimentation with the
consequences and possibilities of the theoretical choices. The goal of
the project is to develop a formal framework and tool for reasoning
about dynamic and reflective modifications in open distributed
systems, ensuring reliability and correctness of the overall system.

These issues will be investigated in the context of @acronym{CREOL}, an
experimental high-level object-oriented language for distributed
objects. The name is an acronym for Concurrent Reflective
Object-oriented Language. The language is based on concurrent objects
communicating by means of asynchronous method calls, and is formally
defined with an operational semantics expressed in rewriting
logic.

Specifications in rewriting logic are executable in the rewriting
logic tool Maude. A prototype Maude interpreter for the communication
basis of the @acronym{CREOL} language has been developed and extended with a
pseudo-deterministic rewrite strategy in order to better simulate the
non-determinism of a distributed environment.


@node Features of CREOL
@section Features of @acronym{CREOL}

@acronym{CREOL} is a @emph{strongly typed} language, in the sense that function
and method calls which disregard data types are rejected.

@acronym{CREOL} is a @emph{statically typed} language.  The compiler tries to
infer, whether a function call or a method call is safe in the sense
that it will succeed.  Programs in which a call cannot succeed because
of the type of an operation or a method are rejected.

Message dispatch in @acronym{CREOL} is based not only on the type of the
receiver of the message, but also on the arguments (multiple
dispatch), especially the type of the caller (which is constrained by
the @emph{co-interface} and available in any method body under the
name @code{caller}.

The @code{caller} mechanism is similar to @code{context} in Smalltalk-80,
but it does not, e.g., provide information on the call-chain.

