load creol-logginginterpreter .
mod PROGRAM is
  protecting CREOL-SIMULATOR .
  op state : -> State [ctor] .
  eq state = {
    < "Console" : Class | Inh: noInh, Param: noVid, Att: "output" |-> null,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null,
              Code: assign( ( "output" @ "Console" ) ; list(emp) ) ;
              return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "_" |-> null, Code: skip ;
              return ( emp ) >,
            < "print" : Method | Param: "newstring", "repetitions",
              Att: "newstring" |-> null, "repetitions" |-> null, "reps" |->
              null, "_" |-> null, Code: if ">" ( "repetitions" :: int(0) ) th
              assign( "output" ; "|-" ( "output" :: "newstring" ) ) ;
              assign( "reps" ; "-" ( "repetitions" :: int(1) ) ) ; if
              ">" ( "reps" :: int(0) ) th assign( "output" ; "|-" ( "output"
              :: "newstring" ) ) el skip fi el skip fi ; return ( emp ) >,
      Ocnt: 0 >
    
    < "Hello" : Class | Inh: noInh, Param: "repetitions_init",
      Att: "repetitions_init" |-> null, "console" |-> null,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null,
              Code: new( "console" ; "Console" ; emp ) ; return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "ccglab1" |-> null,
              "ccglab0" |-> null, "x" |-> null, "_" |-> null,
              Code: assign( "x" ; "repetitions_init" ) ; call( "ccglab0" ;
              "console" ; "print" ; str("hello, world") :: "x" ) ;
              get( "ccglab0" ; noVid ) ; free( "ccglab0" ) ; await ">" ( "x"
              :: int(3) ) ; call( "ccglab1" ; "console" ; "print" ;
              str("hello, world2") :: "-" ( "x" :: int(2) ) ) ;
              get( "ccglab1" ; noVid ) ; free( "ccglab1" ) ; return ( emp ) >,
      Ocnt: 0 > } .
endm

