load creol-modelchecker .
mod PROGRAM is
  protecting CREOL-SIMULATOR .
  op state : -> State [ctor] .
  eq state = {
    < "Philosopher" : Class | Inh: noInh, Param: "butler", Att: "butler" |->
      null, "hungry" |-> null, "chopstick" |-> null, "neighbor" |-> null,
      Mtds: < "init" : Method | Param: noVid, Att: "ccglab0" |-> null, "_"
              |-> null, Code: assign( "chopstick" ; bool(true) ) ;
              assign( "hungry" ; bool(false) ) ; call( "ccglab0" ; "butler" ;
              "getNeighbor" ; emp ) ; get( "ccglab0" ; "neighbor" ) ;
              free( "ccglab0" ) ; return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "ccglab1" |-> null,
              "ccglab0" |-> null, "_" |-> null,
              Code: call( "ccglab0" ; "this" ; "think" ; emp ) ;
              free( "ccglab0" ) ; call( "ccglab1" ; "this" ; "eat" ; emp ) ;
              free( "ccglab1" ) ; return ( emp ) >,
            < "eat" : Method | Param: noVid, Att: "ccglab2" |-> null,
              "ccglab1" |-> null, "ccglab0" |-> null, "_" |-> null,
              Code: await "hungry" ; call( "ccglab0" ; "neighbor" ;
              "borrowStick" ; emp ) ; await ?("ccglab0") ;
              get( "ccglab0" ; noVid ) ; free( "ccglab0" ) ; await
              "chopstick" ; assign( "hungry" ; bool(false) ) ;
              call( "ccglab1" ; "neighbor" ; "returnStick" ; emp ) ;
              free( "ccglab1" ) ; call( "ccglab2" ; "this" ; "eat" ; emp ) ;
              free( "ccglab2" ) ; return ( emp ) >,
            < "think" : Method | Param: noVid, Att: "ccglab0" |-> null, "_"
              |-> null, Code: await "~" ( "hungry" ) ; release ;
              assign( "hungry" ; bool(true) ) ;
              call( "ccglab0" ; "this" ; "think" ; emp ) ; free( "ccglab0" )
              ; return ( emp ) >,
            < "borrowStick" : Method | Param: noVid, Att: "_" |-> null,
              Code: await "chopstick" ; assign( "chopstick" ; bool(false) ) ;
              return ( emp ) >,
            < "returnStick" : Method | Param: noVid, Att: "_" |-> null,
              Code: assign( "chopstick" ; bool(true) ) ; return ( emp ) >,
      Ocnt: 0 >
    
    < "Butler" : Class | Inh: noInh, Param: noVid, Att: "p1" |-> null, "p2"
      |-> null, "p3" |-> null,
      Mtds: < "init" : Method | Param: noVid, Att: "_" |-> null, Code: skip ;
              return ( emp ) >,
            < "run" : Method | Param: noVid, Att: "_" |-> null,
              Code: new( "p1" ; "Philosopher" ; "this" ) ;
              new( "p2" ; "Philosopher" ; "this" ) ;
              new( "p3" ; "Philosopher" ; "this" ) ; return ( emp ) >,
            < "getNeighbor" : Method | Param: noVid, Att: "neighbor" |->
              null, "_" |-> null, Code: if "=" ( "caller" :: "p1" ) th
              assign( "neighbor" ; "p2" ) el if "=" ( "caller" :: "p2" ) th
              assign( "neighbor" ; "p3" ) el assign( "neighbor" ; "p1" ) fi
              fi ; return ( "neighbor" ) >,
      Ocnt: 0 > } .
endm

mod PROGRAM-CHECKER is
  protecting MODEL-CHECKER .
  protecting PROGRAM .
  protecting CREOL-PREDICATES .
endm
